# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

# Align linter with formatter: no spaces inside braces
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
