---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/ping":
    get:
      summary: Ping the API
      tags:
      - Health
      responses:
        '200':
          description: ok
servers:
- url: http://localhost:3000
